name: CI
on:
  pull_request:
    branches: [main]
jobs:
  # Global
  # ================================================

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: yarn lint

  # Browsers
  # ================================================

  build-and-test-browsers:
    name: 'Build and Test Browsers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: yarn build
      - run: yarn test:browser

  # Node 16
  # ================================================

  build-and-test-16:
    name: 'Build and Test Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - run: yarn test:nodejs

  # Node 14
  # ================================================

  build-and-test-14:
    name: 'Build and Test Node 14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - run: yarn test:nodejs

  # Node 12
  # ================================================

  build-and-test-12:
    name: 'Build and Test Node 12'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
      - run: yarn test:nodejs
