name: CI
on:
  pull_request:
    branches: [main]
jobs:
  # Global
  # ================================================

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: yarn lint

  # Browsers
  # ================================================

  build-and-test-browsers:
    name: 'Build and Test Browsers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: yarn build
      - run: yarn test:browser

  build-and-test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Build and Test Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
      - run: yarn test:nodejs
