name: CI
on:
  push:
  pull_request:
    branches: [main]
jobs:
  # Global
  # ================================================

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # version should match .nvmrc
      - run: yarn install
      - run: yarn lint

  # Node 16
  # ================================================

  build-16:
    name: 'Build Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build

  tests-16:
    name: 'Tests Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test:nodejs

  # Node 14
  # ================================================

  build-14:
    name: 'Build Node 14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build

  tests-14:
    name: 'Tests Node 14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test:nodejs

  # Node 12
  # ================================================

  build-12:
    name: 'Build Node 12'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build

  tests-12:
    name: 'Tests Node 12'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test:nodejs
