name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: yarn install
      - name: Lint
        run: yarn lint

  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build

      - name: Test browsers
        run: yarn test:browser

      - name: Switch to Node 16
        uses: actions/setup-node@v2
        with:
          node-version-file: '16'
      - name: Test Node 16
        run: yarn test:nodejs

      - name: Switch to Node 14
        uses: actions/setup-node@v2
        with:
          node-version-file: '14'
      - name: Test Node 14
        run: yarn test:nodejs

      - name: Switch to Node 12
        uses: actions/setup-node@v2
        with:
          node-version-file: '12'
      - name: Test Node 12
        run: yarn test:nodejs
